name: Bug report
description: Create a report to help improve the addon.
title: "[BUG] Short Description"
labels: bug
body:
- type: textarea
  attributes:
    label: Bug
    description: A clear and concise description of what you're experiencing. Do NOT combine multiple bugs into one issue. If you have multiple bugs to report please open separate issues for EACH bug.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Result
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the bug. This is very important.
    placeholder: |
      1. Go to ...
      2. Click on ...
      3. Scroll to ...
      4. See error ...
  validations:
    required: false
- type: textarea
  attributes:
    label: Kodi Version, Type of Device, Logs, Screenshots, and Additional Info
    description: |
      Provide any relevant additional information such as screenshots, log files, or other details here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Checklist
    description: Before submitting your bug report.
    options:
    - label: I have included the version of Kodi I'm using and Device in my report.
      required: true
    - label: I have made a separate issue for each bug that I am reporting.
      required: true
    - label: I have verified this is not a setting.
      required: true
